### ISSUE TITLE
nhdplus.ipynb returns empty geometry

### ISSUE THREAD

**Issue by jjstarn-usgs** [cheginit/HyRiver-examples#12]
The notebook nhdplus.ipynb has been working up until today.  I haven't used it in a couple weeks, so I don't know when the problem started. Now I get this:
![2021-10-07_10-15-06](https://user-images.githubusercontent.com/6577137/136403526-185baa3f-6087-4aad-bd6c-b6c91a598d59.png)

**Comment by cheginit** [comment]
I cannot reproduce the error with the latest versions installed. Can you please show the out of this:

```python
import pynhd

pynhd.show_versions()
```

**Comment by jjstarn-usgs** [comment]
I re-downloaded the notebook and reinstalled the environment that you had sent me a couple weeks ago.  Still get this:



Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
From: Taher Chegini ***@***.***>
Sent: Thursday, October 7, 2021 11:14 AM
To: cheginit/HyRiver-examples ***@***.***>
Cc: Starn, Jeffrey ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cheginit/HyRiver-examples] nhdplus.ipynb returns empty geometry (#12)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I cannot reproduce the error with the latest versions installed. Can you please show the out of this:

import pynhd

pynhd.show_versions()

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2FHyRiver-examples%2Fissues%2F12%23issuecomment-937890593&data=04%7C01%7Cjjstarn%40usgs.gov%7C988dc9ed7f554551a1bb08d989a549a1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637692165268559898%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YJ3XhT2G9LVHwdIBf%2FJ3m7HmCJ42frWGf5YTUqbfcnM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSFX4M3CRFNMC7R2QVBIADUFW2PBANCNFSM5FRNE2CA&data=04%7C01%7Cjjstarn%40usgs.gov%7C988dc9ed7f554551a1bb08d989a549a1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637692165268569863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1m16lcFrsZzC7UAyZ4r3wjVYrZY2mq%2BBCZ2AOoeNPv4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjjstarn%40usgs.gov%7C988dc9ed7f554551a1bb08d989a549a1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637692165268569863%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hIiu43XCReicndubzpIBUcAwRc4cLdkYcFUbMQWaxW0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjjstarn%40usgs.gov%7C988dc9ed7f554551a1bb08d989a549a1%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637692165268579819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vjNfpM2SdRTCYYtVmGqjMdIFsksx5Zzbs4Z3AcsXFCQ%3D&reserved=0>.

**Comment by cheginit** [comment]
It seems that since you're responding through email, the attachments are not shown here on Github. I am not seeing any screenshot or the output of `show_versions` function.

**Comment by cheginit** [comment]
I updated the [env](https://github.com/cheginit/HyRiver-examples/blob/main/environment.yml) file last night to bump the versions. I also reran all the notebooks including [nhdplus.ipynb](https://github.com/cheginit/HyRiver-examples/blob/main/notebooks/nhdplus.ipynb). Things seems to be working. I suspect there's an issue with the latest GDAL. I released new versions for `py3ep`, `pydaymet`, and `pygeoutils` over the last couple of days.

**Comment by cheginit** [comment]
@jjstarn-usgs Were you able to resolve this issue?

**Comment by jjstarn-usgs** [comment]
yes, thank you.  I look forward to using your software.

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
From: Taher Chegini ***@***.***>
Sent: Sunday, November 14, 2021 12:50 AM
To: cheginit/HyRiver-examples ***@***.***>
Cc: Starn, Jeffrey ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [cheginit/HyRiver-examples] nhdplus.ipynb returns empty geometry (#12)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jjstarn-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjjstarn-usgs&data=04%7C01%7Cjjstarn%40usgs.gov%7Cffaa2db18c564dc9279d08d9a732b1a4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637724658457699578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QVrCP2qvBYwQJ3dwINaAdj5vrmtklekZIXPwXoAgq%2Bs%3D&reserved=0> Were you able to resolve this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2FHyRiver-examples%2Fissues%2F12%23issuecomment-968211523&data=04%7C01%7Cjjstarn%40usgs.gov%7Cffaa2db18c564dc9279d08d9a732b1a4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637724658457699578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dO0KjsakGNBUbqIeaBHc9IKzhtjhAVWUhwVn6kYDliY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSFX4KLLLKW5W4LEPG5SY3UL5E2HANCNFSM5FRNE2CA&data=04%7C01%7Cjjstarn%40usgs.gov%7Cffaa2db18c564dc9279d08d9a732b1a4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637724658457709534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Es3%2FFZkjmrVCxX5IfMASVvlIvbttIoB0s2fAMLq6Vb8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjjstarn%40usgs.gov%7Cffaa2db18c564dc9279d08d9a732b1a4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637724658457709534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q3%2BdlaxnRtbb1pYiGTYmslCMbi0TyR6c6lvXDhxq0TQ%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjjstarn%40usgs.gov%7Cffaa2db18c564dc9279d08d9a732b1a4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637724658457719489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xCqxWyFDNHqc2Lp51UgJqommy5xQRjH0lRM9i9Nznz0%3D&reserved=0>.

**Comment by cheginit** [comment]
Great!
