### ISSUE TITLE
Pull every 8 days for ssebop modis data to improve speed?

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [cheginit/HyRiver-examples#17]
Hello again @cheginit,

This is a low priority question/request, but I was curious if you had any thoughts on it. I was looking at your ssebop.ipynb notebook to pull Actual Evapotranspiration, and as your tutorial warns, the speed is painfully slow do the download speed limit. I was wondering:

1) Have you thought about adding an option where it only pulls every 8 days instead of every day? I thought the original MODIS data that this is based on is based on measurements every 8-days and so the others are just estimated. I actually made a loop myself that pulls once a month, and it seems to greatly improve my speed:

```
dates = []
for year in range(2019,2020):
    for month in range(1,13):
           dates.append(f"{year}-{month}-15")


date_index = pd.to_datetime(dates)
variables = ['ET']

ET_date_index_df = pd.DataFrame(index = date_index, columns = variables)

geometry = NLDI().get_basins("01315500").geometry[0]

for date in dates:
    raw_ET = gh.ssebopeta_bygeom(geometry, (date,date))
    ET_date_index_df.loc[date,'ET'] = raw_ET.mean(dim=["x","y"]).values

print(ET_date_index_df)
```

1a) This brings me to another question I'm more interested in but have no one to ask, do you have any idea why the MODIS numbers every 8-days are so bunched. I.e. I'd think they'd be linearly interpolated (or something like that) but instead they seem to just vary 2-3% until the new measurement is made:

array([
       0.58044531, 0.58101023, 0.58048447, 0.58046718, 0.58140967, 0.57954552, 0.57987332, 0.58037438, 
       0.65730487, 0.66724806, 0.65337826, 0.65928052, 0.64592025, 0.64638885, 0.65957057, 0.6691355 , 
       0.57515632, 0.57546295, 0.57430628, 0.57415843, 0.57641179, 0.57451059,0.57677488, 0.57785745, 
       0.59679534, 0.59429464, 0.59588779, 0.59403564, 0.59586239, 0.59482675, 0.59550953, 0.59623959,
       1.09006422, 1.11165737, 1.10637897, 1.15064502, 1.12153352, 1.10236838, 1.12124347, 1.15705575,
       0.83483663, 0.86657869,  0.86202364, 0.87605046, 0.88981404, 0.88260586, 0.86181616, 0.82899753,
        1.24760339, 1.25930346, 1.26045448])

No worries, if you have nothing to say here, in any case I wanted to say thanks for the package and tutorial!

**Comment by cheginit** [comment]
Hi,

> Have you thought about adding an option where it only pulls every 8 days instead of every day?

Since it's easy to do on the user side, there's no need to include such an option. There some other datasets that are monthly or annual summaries instead of daily that I included. There are other Python packages that can pull those data so I didn't include them in PyGeoHydro.

> do you have any idea why the MODIS numbers every 8-days are so bunched

I am not really sure.

> No worries, if you have nothing to say here, in any case I wanted to say thanks for the package and tutorial!

Thanks!

**Comment by Flash-Of-Thunder** [comment]
Well said! I'm having another interesting phenomena come up and I'm wondering if this has to do with the way pygeohydro.ssebopeta_bygeom saves temp data or if I'm missing something on my end. Basically I tried to create a loop to do what we talked about above, but then when I tried to download 20 years of ET data for 1 basin I somehow created 60 GBs of data in temp files when I was expecting more like ~27 KBs in the end.

I ran the following:
```

from pynhd import NLDI
from pyproj import Geod
import datetime
import pygeohydro as gh
import pandas as pd
import os
import glob
import time

# Function to create a list of datetimes every 8 days
def perdelta(start, end, delta):
    dates = []
    curr = start
    dates.append(curr)
    while curr + delta < end:
        curr += delta
        dates.append(curr)
    return(dates)

start_date = datetime.date(2000, 1, 1)
end_date = datetime.date(2020, 12, 31)

dates = pd.to_datetime(perdelta(start_date, end_date, datetime.timedelta(days=8)))

# Replace this with any value e.g. "06409000"
basins_531 = pd.read_csv("C:/Users/samson/Downloads/530_trimmed.txt",header=None, dtype=str).values.ravel()


for basin in basins:
    ET_date_index_df = pd.DataFrame(index = dates, columns = variables)
    geometry = NLDI().get_basins(basin).geometry[0]
    for day in dates:
        raw_ET = gh.ssebopeta_bygeom(geometry, (day,day))
        ET_date_index_df.loc[day,] = raw_ET.mean(dim=["x","y"]).values[0]
    ET_date_index_df.to_csv(f"D:/ET/{basin}.csv")
```

So this created the cache folder in my working directory and that was fine. But before I could even get 1 basin downloaded I had 60 gbs of temp files in C:/Users/flashy_thunder_boi/AppData/Local/Temp/ 

I deleted all the files because my tiny 250 internal SSD was full, but I could rerun the script and see what files are being saved there. 

Cheers!

**Comment by cheginit** [comment]
The cache folder holds the request/response caching database which is a `sqlite` file. This database contain all the requests/responses that you've made when running your code in that specific folder.

The files that are created in you Temp folder, however, are because of the unzipping operations. The AET files on the server are zip files that this function downloads, unzips, and then samples at the specified bounds. Since these files contain AET over CONUS they could be large.

**Comment by Flash-Of-Thunder** [comment]
I see I see. This is very helpful. So perhaps my solution to this is just to add a line in the code that deletes AET files in my temp folder after I've used them since I'm assuming the code doesn't use them again.

Cheers!

**Comment by Flash-Of-Thunder** [comment]
On the slim chance anyone runs into the same problem and wants the same inelegant solution. I added the following to my for day in dates loop:


```
    for day in dates:

        raw_ET = gh.ssebopeta_bygeom(geometry, (day,day))
        ET_date_index_df.loc[day,] = raw_ET.mean(dim=["x","y"]).values[0]

        raw_ET.close()
        nc_files = glob.glob("C:/Users/flashy_mc_flashers/AppData/Local/Temp/*.nc")
        for i in nc_files:
            try:
                os.remove(i)
            except:
                continue

```
